@startuml

interface HealthCalc {
    + idealWeight(height: int, gender: char): float
    + basalMetabolicRate(weight: float, height: int, gender: char, age: int): float
}

class HealthCalcImpl {
    - instance: HealthCalcImpl
    - HealthCalcImpl()
    + getInstance(): HealthCalcImpl
    + idealWeight(height: int, gender: char): float
    + basalMetabolicRate(weight: float, height: int, gender: char, age: int): float
}

HealthCalcImpl ..|> HealthCalc

@enduml
